/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Morning Night Dream - AppGateway
 * This is the AppGateway API documentation.
 * OpenAPI spec version: 0.0.1
 */
import useSwr from 'swr'
import type {
  SWRConfiguration,
  Key
} from 'swr'
import type {
  V1AuthSignUpBody,
  V1AuthSignInBody,
  V1UnauthorizedResponse,
  V1AuthRefreshParams,
  V1AuthResignBody,
  V1SignParams
} from '.././model'
import { customInstance } from '.././client';


  
  // eslint-disable-next-line
  type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

/**
 * サインアップ
 * @summary サインアップ
 */
export const v1AuthSignUp = (
    v1AuthSignUpBody: V1AuthSignUpBody,
 options?: SecondParameter<typeof customInstance>) => {
      return customInstance<void>(
      {url: `/v1/auth/signup`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: v1AuthSignUpBody
    },
      options);
    }
  

/**
 * サインイン
 * @summary サインイン
 */
export const v1AuthSignIn = (
    v1AuthSignInBody: V1AuthSignInBody,
 options?: SecondParameter<typeof customInstance>) => {
      return customInstance<void>(
      {url: `/v1/auth/signin`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: v1AuthSignInBody
    },
      options);
    }
  

/**
 * 検証
 * @summary 検証
 */
export const v1AuthVerify = (
    
 options?: SecondParameter<typeof customInstance>) => {
      return customInstance<void>(
      {url: `/v1/auth/verify`, method: 'get'
    },
      options);
    }
  

export const getV1AuthVerifyKey = () => [`/v1/auth/verify`];

    
export type V1AuthVerifyQueryResult = NonNullable<Awaited<ReturnType<typeof v1AuthVerify>>>
export type V1AuthVerifyQueryError = V1UnauthorizedResponse

export const useV1AuthVerify = <TError = V1UnauthorizedResponse>(
  options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof v1AuthVerify>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }

  ) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
    const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getV1AuthVerifyKey() : null);
  const swrFn = () => v1AuthVerify(requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * リフレッシュ
 * @summary リフレッシュ
 */
export const v1AuthRefresh = (
    params: V1AuthRefreshParams,
 options?: SecondParameter<typeof customInstance>) => {
      return customInstance<void>(
      {url: `/v1/auth/refresh`, method: 'get',
        params
    },
      options);
    }
  

export const getV1AuthRefreshKey = (params: V1AuthRefreshParams,) => [`/v1/auth/refresh`, ...(params ? [params]: [])];

    
export type V1AuthRefreshQueryResult = NonNullable<Awaited<ReturnType<typeof v1AuthRefresh>>>
export type V1AuthRefreshQueryError = unknown

export const useV1AuthRefresh = <TError = unknown>(
 params: V1AuthRefreshParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof v1AuthRefresh>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }

  ) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
    const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getV1AuthRefreshKey(params) : null);
  const swrFn = () => v1AuthRefresh(params, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * サインアウト
 * @summary サインアウト
 */
export const v1AuthSignOut = (
    
 options?: SecondParameter<typeof customInstance>) => {
      return customInstance<void>(
      {url: `/v1/auth/signout`, method: 'get'
    },
      options);
    }
  

export const getV1AuthSignOutKey = () => [`/v1/auth/signout`];

    
export type V1AuthSignOutQueryResult = NonNullable<Awaited<ReturnType<typeof v1AuthSignOut>>>
export type V1AuthSignOutQueryError = unknown

export const useV1AuthSignOut = <TError = unknown>(
  options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof v1AuthSignOut>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }

  ) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
    const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getV1AuthSignOutKey() : null);
  const swrFn = () => v1AuthSignOut(requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * リサイン(退会)
 * @summary リサイン(退会)
 */
export const v1AuthResign = (
    v1AuthResignBody: V1AuthResignBody,
 options?: SecondParameter<typeof customInstance>) => {
      return customInstance<void>(
      {url: `/v1/auth`, method: 'delete',
      headers: {'Content-Type': 'application/json', },
      data: v1AuthResignBody
    },
      options);
    }
  

/**
 * 署名検証
 * @deprecated
 * @summary 署名検証
 */
export const v1Sign = (
    params: V1SignParams,
 options?: SecondParameter<typeof customInstance>) => {
      return customInstance<void>(
      {url: `/v1/sign`, method: 'get',
        params
    },
      options);
    }
  

export const getV1SignKey = (params: V1SignParams,) => [`/v1/sign`, ...(params ? [params]: [])];

    
export type V1SignQueryResult = NonNullable<Awaited<ReturnType<typeof v1Sign>>>
export type V1SignQueryError = unknown

export const useV1Sign = <TError = unknown>(
 params: V1SignParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof v1Sign>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }

  ) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
    const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getV1SignKey(params) : null);
  const swrFn = () => v1Sign(params, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

