/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Morning Night Dream - AppGateway
 * This is the AppGateway API documentation.
 * OpenAPI spec version: 0.0.1
 */
import useSwr from 'swr'
import type {
  SWRConfiguration,
  Key
} from 'swr'
import type {
  V1ListArticleResponse,
  V1ListArticlesParams
} from '.././model'
import { customInstance } from '.././client';


  
  // eslint-disable-next-line
  type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

/**
 * List articles
 * @summary List articles
 */
export const v1ListArticles = (
    params: V1ListArticlesParams,
 options?: SecondParameter<typeof customInstance>) => {
      return customInstance<V1ListArticleResponse>(
      {url: `/v1/article`, method: 'get',
        params
    },
      options);
    }
  

export const getV1ListArticlesKey = (params: V1ListArticlesParams,) => [`/v1/article`, ...(params ? [params]: [])];

    
export type V1ListArticlesQueryResult = NonNullable<Awaited<ReturnType<typeof v1ListArticles>>>
export type V1ListArticlesQueryError = void

export const useV1ListArticles = <TError = void>(
 params: V1ListArticlesParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof v1ListArticles>>, TError> & { swrKey?: Key, enabled?: boolean }, request?: SecondParameter<typeof customInstance> }

  ) => {

  const {swr: swrOptions, request: requestOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
    const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getV1ListArticlesKey(params) : null);
  const swrFn = () => v1ListArticles(params, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

