/* tslint:disable */
/* eslint-disable */
/**
 * Morning Night Dream - AppGateway
 * This is the AppGateway API documentation.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: morning.night.dream@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

/**
 * 
 */
export class VersionApi extends runtime.BaseAPI {

    /**
     * APIバージョン
     * APIバージョン
     */
    async v1APIVersionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/version/api`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * APIバージョン
     * APIバージョン
     */
    async v1APIVersion(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.v1APIVersionRaw(initOverrides);
    }

    /**
     * Coreバージョン
     * Coreバージョン
     */
    async v1CoreVersionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/version/core`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Coreバージョン
     * Coreバージョン
     */
    async v1CoreVersion(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.v1CoreVersionRaw(initOverrides);
    }

}
