/* tslint:disable */
/* eslint-disable */
/**
 * Morning Night Dream - AppGateway
 * This is the AppGateway API documentation.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: morning.night.dream@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1AuthSignUpRequest
 */
export interface V1AuthSignUpRequest {
    /**
     * メールアドレス
     * @type {string}
     * @memberof V1AuthSignUpRequest
     */
    email: string;
    /**
     * パスワード
     * @type {string}
     * @memberof V1AuthSignUpRequest
     */
    password: string;
}

/**
 * Check if a given object implements the V1AuthSignUpRequest interface.
 */
export function instanceOfV1AuthSignUpRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function V1AuthSignUpRequestFromJSON(json: any): V1AuthSignUpRequest {
    return V1AuthSignUpRequestFromJSONTyped(json, false);
}

export function V1AuthSignUpRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1AuthSignUpRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function V1AuthSignUpRequestToJSON(value?: V1AuthSignUpRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
    };
}

