/* tslint:disable */
/* eslint-disable */
/**
 * Morning Night Dream - AppGateway
 * This is the AppGateway API documentation.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: morning.night.dream@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1AuthSignInRequest
 */
export interface V1AuthSignInRequest {
    /**
     * メールアドレス
     * @type {string}
     * @memberof V1AuthSignInRequest
     */
    email: string;
    /**
     * パスワード
     * @type {string}
     * @memberof V1AuthSignInRequest
     */
    password: string;
    /**
     * 公開鍵
     * @type {string}
     * @memberof V1AuthSignInRequest
     */
    publicKey: string;
}

/**
 * Check if a given object implements the V1AuthSignInRequest interface.
 */
export function instanceOfV1AuthSignInRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "password" in value;
    isInstance = isInstance && "publicKey" in value;

    return isInstance;
}

export function V1AuthSignInRequestFromJSON(json: any): V1AuthSignInRequest {
    return V1AuthSignInRequestFromJSONTyped(json, false);
}

export function V1AuthSignInRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1AuthSignInRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'publicKey': json['publicKey'],
    };
}

export function V1AuthSignInRequestToJSON(value?: V1AuthSignInRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
        'publicKey': value.publicKey,
    };
}

